---
language: node_js
node_js:
  - "7"

notifications:
  email: false

sudo: false

env:
  - EMBER_TRY_SCENARIO=ember-2.0
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO --skip-cleanup=true
